<a href="https://colab.research.google.com/github/mekaneeky/GoMyCode-Intro2AI-notebooks/blob/main/GMC_AI_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import math
import mlxtend
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [1]:
dataset = [['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],
        ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],
        ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],
        ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],
      ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]

In [6]:
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)    #Apply one-hot-encoding on our dataset
tx_df=pd.DataFrame(te_ary, columns=te.columns_)  #Creating a new DataFrame from our Numpy array

In [29]:
frequent_itemsets = apriori(tx_df, min_support=0.5, use_colnames=True)

In [30]:
association_rules(frequent_itemsets,metric="lift",min_threshold=1.00)

  antecedents consequents  antecedent support  ...  lift  leverage  conviction
0     (Skirt)     (Pants)                 0.6  ...  1.25      0.12         inf
1     (Pants)     (Skirt)                 0.8  ...  1.25      0.12         1.6

[2 rows x 9 columns]

# Proposed Strategy 1

It appears that "lift" is greater than 1.0 indicating that the Skirts and Pants are more likely to sell together. I propose that a discount would be made on the bundle Skirt + Pants to increase sales.

In [31]:
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7) # associate itemsets with confidence over 70%.

  antecedents consequents  antecedent support  ...    lift  leverage  conviction
0     (Pants)     (Scarf)                 0.8  ...  0.9375     -0.04         0.8
1     (Scarf)     (Pants)                 0.8  ...  0.9375     -0.04         0.8
2     (Skirt)     (Pants)                 0.6  ...  1.2500      0.12         inf
3     (Pants)     (Skirt)                 0.8  ...  1.2500      0.12         1.6

[4 rows x 9 columns]

In [32]:
!gdown --id 109dPPJzZbjzMUp3JQBx5rQ538fzMNYzU

Downloading...
From: https://drive.google.com/uc?id=109dPPJzZbjzMUp3JQBx5rQ538fzMNYzU
To: /content/Market_Basket_Optimisation.csv
100% 303k/303k [00:00<00:00, 43.6MB/s]

In [54]:
big_tx_df = pd.read_csv("Market_Basket_Optimisation.csv", header=None)

In [40]:
big_tx_df.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [55]:
big_tx_lol = big_tx_df.values.tolist()

### Clean NaNs
cleaned_tx_lol = []
for tx_list in big_tx_lol:
    cleaned_tx_list = []
    for tx in tx_list:
        if type(tx) != str:
            continue
        else:
            cleaned_tx_list.append(tx)
    cleaned_tx_lol.append(cleaned_tx_list)

te=TransactionEncoder()
te_ary=te.fit(cleaned_tx_lol).transform(cleaned_tx_lol)    #Apply one-hot-encoding on our dataset
cleaned_tx_df=pd.DataFrame(te_ary, columns=te.columns_)

In [56]:
cleaned_tx_df.head()

    asparagus  almonds  antioxydant juice  ...   yams  yogurt cake  zucchini
0       False     True               True  ...   True        False     False
1       False    False              False  ...  False        False     False
2       False    False              False  ...  False        False     False
3       False    False              False  ...  False        False     False
4       False    False              False  ...  False        False     False

[5 rows x 120 columns]

In [71]:
frequent_itemsets = apriori(cleaned_tx_df, min_support=0.03, use_colnames=True)

In [72]:
association_rules(frequent_itemsets,metric="lift",min_threshold=1.00)

            antecedents          consequents  ...  leverage  conviction
0                (eggs)          (chocolate)  ...  0.003751    1.025603
1           (chocolate)               (eggs)  ...  0.003751    1.028711
2           (chocolate)       (french fries)  ...  0.006393    1.049383
3        (french fries)          (chocolate)  ...  0.006393    1.046827
4                (milk)          (chocolate)  ...  0.010898    1.111823
5           (chocolate)               (milk)  ...  0.010898    1.082736
6           (chocolate)      (mineral water)  ...  0.013604    1.122357
7       (mineral water)          (chocolate)  ...  0.013604    1.073256
8           (spaghetti)          (chocolate)  ...  0.010668    1.079070
9           (chocolate)          (spaghetti)  ...  0.010668    1.085581
10               (eggs)       (french fries)  ...  0.005681    1.039640
11       (french fries)               (eggs)  ...  0.005681    1.042232
12               (milk)               (eggs)  ...  0.007509    1.076009
13               (eggs)               (milk)  ...  0.007509    1.050423
14               (eggs)      (mineral water)  ...  0.008090    1.062815
15      (mineral water)               (eggs)  ...  0.008090    1.043158
16          (spaghetti)               (eggs)  ...  0.005239    1.038081
17               (eggs)          (spaghetti)  ...  0.005239    1.036592
18      (mineral water)  (frozen vegetables)  ...  0.013007    1.064189
19  (frozen vegetables)      (mineral water)  ...  0.013007    1.218270
20      (mineral water)        (ground beef)  ...  0.017507    1.088672
21        (ground beef)      (mineral water)  ...  0.017507    1.305401
22          (spaghetti)        (ground beef)  ...  0.022088    1.163716
23        (ground beef)          (spaghetti)  ...  0.022088    1.373997
24               (milk)      (mineral water)  ...  0.017105    1.209650
25      (mineral water)               (milk)  ...  0.017105    1.089850
26          (spaghetti)               (milk)  ...  0.012900    1.093043
27               (milk)          (spaghetti)  ...  0.012900    1.137061
28           (pancakes)      (mineral water)  ...  0.011071    1.180529
29      (mineral water)           (pancakes)  ...  0.011071    1.054100
30          (spaghetti)      (mineral water)  ...  0.018223    1.159314
31      (mineral water)          (spaghetti)  ...  0.018223    1.102008

[32 rows x 9 columns]

In [68]:
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.3) # associate itemsets with confidence over 70%.

   antecedents      consequents  ...  leverage  conviction
0  (chocolate)  (mineral water)  ...  0.013604    1.122357
1  (spaghetti)  (mineral water)  ...  0.018223    1.159314

[2 rows x 9 columns]

# Proposed Strategy 2

It appears that "lift" is greater than 1.0 mostly for mineral water and other items, bundles of mineral water with other food items should be offered to increase sales. Other food items seem to be popular together such as spaghetti and beef and spaghetti and eggs.